### ISSUE TITLE
any progress?

### ISSUE THREAD

**Issue by vladdd183** [taisprestes01/Pocket-Option-API#1]
Hi, have you made any progress on this project? I needed that api too. So I searched on github for similar projects, found implementation attempts from https://github.com/theshadow76/PocketOptionAPI (code WIP now and do not work) but he got stuck on one bug, I helped him to fix it and move forward, but he can't continue development yet. If you are serious about developing this api, you might find it very useful https://github.com/theshadow76/PocketOptionAPI/issues/4

I have done reverse engineering a web-socket, however I am not very good at creating an api client based on it. So I hope that you will find my code useful and tell me about your progress in this task

**Comment by VampyreBatz** [comment]
if i buy this will i be able to get real time data from the otc WITH VOLUME info? if not how do i get otc data from pocket option?

**Comment by vladdd183** [comment]
> if i buy this will i be able to get real time data from the otc WITH VOLUME info? if not how do i get otc data from pocket option?

Hi, do you want to receive otc data from pocket option? I don't understand about volume info, can you tell more about it?

**Comment by vladdd183** [comment]
> if i buy this will i be able to get real time data from the otc WITH VOLUME info? if not how do i get otc data from pocket option?

I've made a lot of progress in creating an api for the pocket option. So I guess I can help you if you explain in detail what you need. You can write your telegram and I will contact you

**Comment by taisprestes01** [comment]
> Hi, have you made any progress on this project? I needed that api too. So I searched on github for similar projects, found implementation attempts from https://github.com/theshadow76/PocketOptionAPI (code WIP now and do not work) but he got stuck on one bug, I helped him to fix it and move forward, but he can't continue development yet. If you are serious about developing this api, you might find it very useful [theshadow76/PocketOptionAPI#4](https://github.com/theshadow76/PocketOptionAPI/issues/4)
> 
> I have done reverse engineering a web-socket, however I am not very good at creating an api client based on it. So I hope that you will find my code useful and tell me about your progress in this task

Hi, yes I will continue this project. but at the moment I need to finish this other project https://github.com/taisprestes01/Product-Miner thank you for your contribution to resolving the bug. yes this will be useful
